#!/usr/bin/env bash
set -eu

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=release_audit_rules.sh
source "$script_dir/release_audit_rules.sh"

while IFS= read -r -d '' entry; do
    metadata=${entry%%$'\t'*}
    file=${entry#*$'\t'}
    read -r mode object _ <<< "$metadata"

    if [[ $file =~ $release_forbidden ]]; then
        printf '检测到禁止发布的文件：%q\n' "$file" >&2
        exit 1
    fi

    if [ "$mode" = 160000 ]; then
        printf '检测到 gitlink/submodule：%q\n' "$file" >&2
        exit 1
    fi

    size=$(git cat-file -s "$object")
    if [ "$size" -ge "$release_max_bytes" ]; then
        printf '跟踪文件达到或超过 50 MiB：%q\n' "$file" >&2
        exit 1
    fi

    if git cat-file blob "$object" | LC_ALL=C grep -aE -q -- "$release_mac_user_path"; then
        printf '跟踪文件包含本机绝对路径：%q\n' "$file" >&2
        exit 1
    fi

    if git cat-file blob "$object" | LC_ALL=C grep -aE -q -- "$release_pem_header"; then
        printf '跟踪文件包含私钥 PEM 头：%q\n' "$file" >&2
        exit 1
    fi
done < <(git ls-files -s -z)

python3 - <<'PY'
import hashlib
import json
import subprocess

models = "vision/models"


def index_blob(path: str) -> bytes:
    result = subprocess.run(
        ["git", "show", f":{path}"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise ValueError(f"{path} 必须被 Git 跟踪")
    return result.stdout


manifest_path = f"{models}/vision_models.json"
try:
    manifest = json.loads(index_blob(manifest_path))
    if manifest["license"] != "MIT":
        raise ValueError("license 必须是 MIT")
    if manifest["trainingScript"] != "vision/ml/train.py":
        raise ValueError("trainingScript 必须是 vision/ml/train.py")
    expected_synthetic_data = (
        "Both ONNX models were trained from random initialization on synthetic board data "
        "generated by vision/ml/synthetic_data.py; no third-party model weights or datasets were used."
    )
    if manifest["syntheticData"] != expected_synthetic_data:
        raise ValueError("syntheticData 必须声明合成训练数据和无第三方权重/数据集")
    expected = (
        ("detector", "board_locator.onnx"),
        ("intersectionClassifier", "intersection_classifier.onnx"),
    )
    expected_model_paths = sorted(f"{models}/{filename}" for _, filename in expected)
    tracked_model_paths = sorted(
        path.decode("utf-8", "surrogateescape")
        for path in subprocess.check_output(
            ["git", "ls-files", "-z", "--", f"{models}/*.onnx"]
        ).split(b"\0")
        if path
    )
    if tracked_model_paths != expected_model_paths:
        raise ValueError("vision/models 只能包含两份指定 ONNX")
    for section, filename in expected:
        entry = manifest[section]
        if entry["file"] != filename:
            raise ValueError(f"{section}.file 必须是 {filename}")
        model_path = f"{models}/{filename}"
        actual = hashlib.sha256(index_blob(model_path)).hexdigest()
        if actual != entry["sha256"]:
            raise ValueError(f"{filename} 的 SHA-256 与 manifest 不一致")
except (KeyError, TypeError, UnicodeError, ValueError, json.JSONDecodeError) as error:
    raise SystemExit(f"模型验收失败：{error}")
PY

echo '仓库验收通过'
