from __future__ import annotations

import json
from pathlib import Path
from typing import Any


MODEL_RELEASE_METADATA = {
    "license": "MIT",
    "trainingScript": "vision/ml/train.py",
    "syntheticData": (
        "Both ONNX models were trained from random initialization on synthetic board data "
        "generated by vision/ml/synthetic_data.py; no third-party model weights or datasets were used."
    ),
}


def write_model_manifest(path: Path, report: dict[str, Any]) -> dict[str, Any]:
    complete_report = {**report, **MODEL_RELEASE_METADATA}
    path.write_text(json.dumps(complete_report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return complete_report
